import { execSync } from "node:child_process";

const cmd = (line: string) => execSync(line, { stdio: "inherit" });

cmd(`npx ts-node scripts/generate-wod.ts --title-en "The Awakening" --title-fr "L Eveil" --title-es "El Despertar" --type amrap --objective conditioning --content-en "AMRAP 20: 5 Pull-ups / 10 Push-ups / 15 Air Squats\nScale: Ring Rows / Knee Push-ups / Goblet Squats @16kg\nRX+: Chest-to-Bar / HSPU / OHS @35kg" --content-fr "AMRAP 20: 5 Pull-ups / 10 Push-ups / 15 Air Squats\nScale: Ring Rows / Knee Push-ups / Goblet Squats @16kg\nRX+: Chest-to-Bar / HSPU / OHS @35kg" --content-es "AMRAP 20: 5 Pull-ups / 10 Push-ups / 15 Air Squats\nScale: Ring Rows / Knee Push-ups / Goblet Squats @16kg\nRX+: Chest-to-Bar / HSPU / OHS @35kg" --components gymnastics,cardio --tags calisthenics,bodyweight,beginner-friendly,metcon --duration 20 --avg-hr 155 --calories 280 --intensity moderate --load 210 --publish`);
cmd(`npx ts-node scripts/generate-wod.ts --title-en "Iron Rain" --title-fr "Pluie de Fer" --title-es "Lluvia de Hierro" --type for_time --objective strength --content-en "21-15-9: Deadlift @100/70kg, Box Jump 60/50cm, Burpee Over Bar" --content-fr "21-15-9: Souleve de terre @100/70kg, Box Jump 60/50cm, Burpee Over Bar" --content-es "21-15-9: Peso muerto @100/70kg, Box Jump 60/50cm, Burpee Over Bar" --components weightlifting,cardio --tags deadlift,strength,iconic,barbell --duration 22 --avg-hr 165 --calories 320 --intensity high --load 340 --publish`);
cmd(`npx ts-node scripts/generate-wod.ts --title-en "Clockwork" --title-fr "Mecanisme" --title-es "Relojeria" --type emom --objective power --content-en "EMOM 30: Odd -> 3 Power Cleans @70/50kg | Even -> 10 Toes-to-Bar" --content-fr "EMOM 30: Odd -> 3 Power Cleans @70/50kg | Even -> 10 Toes-to-Bar" --content-es "EMOM 30: Odd -> 3 Power Cleans @70/50kg | Even -> 10 Toes-to-Bar" --components weightlifting,gymnastics --tags emom,olympic-lifting,core,power --duration 30 --avg-hr 148 --calories 290 --intensity high --load 300 --publish`);
cmd(`npx ts-node scripts/generate-wod.ts --title-en "The Grinder" --title-fr "Le Broyeur" --title-es "La Trituradora" --type chipper --objective endurance --content-en "100 Double Unders / 80 Wall Balls @9/6kg / 60 KB Swings @24/16kg / 40 Pull-ups / 20 Hang Cleans @60/42kg" --content-fr "100 Double Unders / 80 Wall Balls @9/6kg / 60 KB Swings @24/16kg / 40 Pull-ups / 20 Hang Cleans @60/42kg" --content-es "100 Double Unders / 80 Wall Balls @9/6kg / 60 KB Swings @24/16kg / 40 Pull-ups / 20 Hang Cleans @60/42kg" --components cardio,weightlifting,gymnastics --tags chipper,cardio,endurance,benchmark --duration 32 --calories 380 --intensity extreme --recovery 48 --load 420 --publish`);
cmd(`npx ts-node scripts/generate-wod.ts --title-en "Ladder to Hell" --title-fr "Echelle vers l Enfer" --title-es "Escalera al Infierno" --type ladder --objective strength --content-en "1->10: Squat Snatch @50/35kg + Bar Muscle-Up (1:2 ratio) / Every 2 min: 200m Run" --content-fr "1->10: Squat Snatch @50/35kg + Bar Muscle-Up (1:2 ratio) / Every 2 min: 200m Run" --content-es "1->10: Squat Snatch @50/35kg + Bar Muscle-Up (1:2 ratio) / Every 2 min: 200m Run" --components weightlifting,gymnastics,cardio --tags snatch,muscle-up,ladder,advanced --duration 35 --avg-hr 172 --intensity extreme --load 460 --publish`);
